@startuml
interface "ClassDefinition" as Component {
}

class "User" as ConcreteComponent {
}

abstract class "MetadataDecorator" as Decorator {
    - component: ClassDefinition
}

annotation "@Entity" as EntityDecorator {
    + Entity(tableName)
}

annotation "@Column" as ColumnDecorator {
    + Column(options)
}

annotation "@OneToOne" as OneToOneDecorator {
    + OneToOne(typeFunction, options)
}

annotation "@OneToMany" as OneToManyDecorator {
    + OneToMany(typeFunction, inverseSide, options)
}

annotation "@ManyToOne" as ManyToOneDecorator {
    + ManyToOne(typeFunction, inverseSide, options)
}

annotation "@ManyToMany" as ManyToManyDecorator {
    + ManyToMany(typeFunction, options)
}

Component <|.. ConcreteComponent
Component <|.. Decorator
Decorator o-- Component
Decorator <|-- EntityDecorator
Decorator <|-- ColumnDecorator
Decorator <|-- OneToOneDecorator
Decorator <|-- OneToManyDecorator
Decorator <|-- ManyToOneDecorator
Decorator <|-- ManyToManyDecorator
@enduml
